/*****************************************************************
* FILE DESCRIPTION:
----------------------------------------------------------------
 *  file    : Port_Lcfg.c
 *  details : Source file for link time configurations PORT Driver.
 *****************************************************************/

/******************************************
  INCLUDES
 *******************************************/
#include "STD_TYPES.h"
#include "Port_types.h"
#include "Port_cfg.h"

#define CLCD_RS_PIN   CLCD_PA3
#define CLCD_E_PIN    CLCD_PA2

#define CLCD_D4_PIN   CLCD_PB0
#define CLCD_D5_PIN   CLCD_PB1
#define CLCD_D6_PIN   CLCD_PB2
#define CLCD_D7_PIN   CLCD_PB4

/******************************************
  Global Data
 *******************************************/
const Port_Configtype Port_ConfigArr[PORT_PINS_CONFIG_ARR_SIZE] = {

		{PORT_PA3 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING},//RS
		{PORT_PD6 , PORT_LOW , PORT_INPUT, PORT_PULLUP},   //ICP
		{PORT_PA2 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //E
		{PORT_PB0 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //D4
		{PORT_PB1 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //D5
		{PORT_PB2 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //D6
		{PORT_PB4 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //D7
		{PORT_PC0 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //Trig

							   //KEYPAD
		{PORT_PC5 , PORT_LOW , PORT_INPUT, PORT_PULLUP},    //ROW0
		{PORT_PC4 , PORT_LOW , PORT_INPUT, PORT_PULLUP},    //ROW1
		{PORT_PC3 , PORT_LOW , PORT_INPUT, PORT_PULLUP},    //ROW2
		{PORT_PC2 , PORT_LOW , PORT_INPUT, PORT_PULLUP},    //ROW3
		{PORT_PD7 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //COL0 (PushButton#1) (configured as input in DirectMode)
		{PORT_PD6 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //COL1
		{PORT_PD5 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //COL2
		{PORT_PD3 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //COL3

		{PORT_PA6 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //Yellow LED
		{PORT_PA5 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //BLUE LED
		{PORT_PA4 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //GREEN LED
		{PORT_PB7 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //RED LED
		{PORT_PB3 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //OC0

		{PORT_PC0 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //SCL
		{PORT_PC1 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //SDA


		{PORT_PD1 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //TX
		{PORT_PC0 , PORT_LOW , PORT_INPUT, PORT_PULLUP}, //RX


};


/****************  SmallOS Port Configuration   *************/
const Port_Configtype SmallOS_PortConfig_ARR[SmallOS_PortConfig_ARR_SIZE] = {

							//LCD  (optional)
		{PORT_PA3 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING},//RS
		{PORT_PD6 , PORT_LOW , PORT_INPUT, PORT_PULLUP},   //ICP
		{PORT_PA2 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //E
		{PORT_PB0 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //D4
		{PORT_PB1 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //D5
		{PORT_PB2 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //D6
		{PORT_PB4 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //D7
		{PORT_PC0 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //Trig

							   //KEYPAD (All Optional But {PushButton#1})
		{PORT_PC5 , PORT_LOW , PORT_INPUT, PORT_PULLUP},    //ROW0
		{PORT_PC4 , PORT_LOW , PORT_INPUT, PORT_PULLUP},    //ROW1
		{PORT_PC3 , PORT_LOW , PORT_INPUT, PORT_PULLUP},    //ROW2
		{PORT_PC2 , PORT_LOW , PORT_INPUT, PORT_PULLUP},    //ROW3
		{PORT_PD7 , PORT_LOW , PORT_INPUT, PORT_FLOATING}, //COL0
		{PORT_PD6 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //COL1
		{PORT_PD5 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //COL2
/*CARE*/{PORT_PD3 , PORT_LOW , PORT_INPUT, PORT_PULLUP}, //COL3 (PushButton#4) (configured as input in DirectMode)
								//LEDs (All Mandatory But {Yellow LED -PA6-})
		{PORT_PA6 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //Yellow LED
		{PORT_PA5 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //BLUE LED
		{PORT_PA4 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //GREEN LED
		{PORT_PB7 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //RED LED



};


/****************  Configurable Duty & freq Port ConfigArr   *************/
const Port_Configtype Configurable_Duty_freq_Port_ConfigArr[Configurable_Duty_freq_PortConfig_ARR_SIZE] = {
							//LCD  (optional)
		{PORT_PA3 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING},//RS
		{PORT_PD6 , PORT_LOW , PORT_INPUT, PORT_PULLUP},   //ICP
		{PORT_PA2 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //E
		{PORT_PB0 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //D4
		{PORT_PB1 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //D5
		{PORT_PB2 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //D6
		{PORT_PB4 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //D7
		{PORT_PC0 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //Trig
							   //KEYPAD (All Optional But {PushButton#1})
		{PORT_PC5 , PORT_LOW , PORT_INPUT, PORT_PULLUP},    //ROW0
		{PORT_PC4 , PORT_LOW , PORT_INPUT, PORT_PULLUP},    //ROW1
		{PORT_PC3 , PORT_LOW , PORT_INPUT, PORT_PULLUP},    //ROW2
		{PORT_PC2 , PORT_LOW , PORT_INPUT, PORT_PULLUP},    //ROW3
		{PORT_PD7 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //COL0
		{PORT_PD6 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //COL1
		{PORT_PD5 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //COL2
		{PORT_PD3 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //COL3
								//LEDs (Optional)
		{PORT_PA6 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //Yellow LED
		{PORT_PA5 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //BLUE LED
		{PORT_PA4 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //GREEN LED
		{PORT_PB7 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //RED LED
								//Motor Driver Pins
		{PORT_PB3 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //PWN   -> OC0 pin
		{PORT_PB5 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //DIR
		{PORT_PB6 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //EN

};




/****************  Configurable Duty & freq Port ConfigArr   *************/
const Port_Configtype LoginSystem_Port_ConfigArr[Configurable_Duty_freq_PortConfig_ARR_SIZE] = {
							//LCD  (optional)
		{PORT_PA3 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING},//RS
		{PORT_PD6 , PORT_LOW , PORT_INPUT, PORT_PULLUP},   //ICP
		{PORT_PA2 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //E
		{PORT_PB0 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //D4
		{PORT_PB1 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //D5
		{PORT_PB2 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //D6
		{PORT_PB4 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //D7
		{PORT_PC0 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //Trig
							   //KEYPAD (All Optional But {PushButton#1})
		{PORT_PC5 , PORT_LOW , PORT_INPUT, PORT_PULLUP},    //ROW0
		{PORT_PC4 , PORT_LOW , PORT_INPUT, PORT_PULLUP},    //ROW1
		{PORT_PC3 , PORT_LOW , PORT_INPUT, PORT_PULLUP},    //ROW2
		{PORT_PC2 , PORT_LOW , PORT_INPUT, PORT_PULLUP},    //ROW3
		{PORT_PD7 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //COL0
		{PORT_PD6 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //COL1
		{PORT_PD5 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //COL2
		{PORT_PD3 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //COL3
								//LEDs (Optional)
		{PORT_PA6 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //Yellow LED
		{PORT_PA5 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //BLUE LED
		{PORT_PA4 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //GREEN LED
		{PORT_PB7 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //RED LED
								//Motor Driver Pins
		{PORT_PB3 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //PWN   -> OC0 pin
		{PORT_PB5 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //DIR
		{PORT_PB6 , PORT_LOW , PORT_OUTPUT, PORT_FLOATING}, //EN

};

